server:
  port: 8080

spring:
  application:
    name: "epam"

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-stg
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-stg.yaml
    drop-first: false

  security:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiration: 900000

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
        disable-thread-pool: true


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: backend

application:
  domain: ${MY_DOMAIN}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      trainer:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3