spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-dev.yaml

  security:
    jwt:
      secret-key: "4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c"
      access-token-expiration: 900000


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: backend