spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-dev.yaml


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: backend