server:
  port: 8080

spring:
  application:
    name: "epam"

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-stg
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-stg.yaml
    drop-first: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: backend