spring:
  application:
    name: "trainer"

  security:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiration: 900000
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:${ACTIVEMQ_PORT}
    user: ${ACTIVEMQ_BROKER_USER}
    password: ${ACTIVEMQ_BROKER_PASSWORD}
    packages:
      trust-all: true

server:
  port: 8082

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] txId=%X{transactionId:-} %logger{36} - %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true



